version: '3.8'

services:

  postgres:
    container_name: wishlist_postgres
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - '8001:5432'
    networks:
      - stack-network
    volumes:
      - ./resources/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  redis:
    container_name: wishlist_redis
    image: redis:6.2.5
    command: redis-server --requirepass 12345
    ports:
      - '8002:6379'
    networks:
      - stack-network

networks:
  stack-network:
    driver: bridge
